### ISSUE TITLE
Dose this support a kotlin android project?

### ISSUE THREAD

**Issue by baishuai** [6thsolution/EasyMVP#22]

**Comment by SaeedMasoumi** [comment]
@baishuai Yes

Here is an example:

```kotlin
@FragmentView(presenter = MyPresenter::class)
class MyFragment : BaseFragment(), MyPresenter.View {

    @Inject
    @Presenter
    lateinit var presenter: MyPresenter

}

class MyPresenter @Inject constructor(val repo: SomeRepository) : AbstractPresenter<MyPresenter.View>() {

 interface View 
}
```

**Comment by baishuai** [comment]
Thanks. @SaeedMasoumi 

I have already tried like your example.
And use `SomeComponent.inject()` before call `super.onCreate(savedInstanceState)`.
But got `lateinit property somePresenter has not been initialized`

The dagger works ok before I use `EasyMVP`

Have you ever fall into this problem?

**Comment by SaeedMasoumi** [comment]
@baishuai No, Maybe there is a problem with your dagger's component to provide the presenter or you invoke your presenter too early (before `Activity#onStart` or `Fragment#onResume` because EasyMVP uses Loaders)

This is my approach to provide a presenter:

- For each Fragment/Activity, I have a subcomponent
```kotlin
    @Subcomponent(modules = MyModule.class)
    @PerFragment
    interface MyComponent {
        void injectTo(MyFragment fragment);
    }
```

- Make presenter constructor injectable
```kotlin
class MyPresenter @Inject constructor(....
```
- Before `super.onCreate`, I inject my dependencies
```kotlin
appComponent.plus(MyModule()).injectTo(this)
```
- Now you can use presenter after `Activity#onStart` or `Fragment#onResume`

**Comment by baishuai** [comment]
Now it works. I have used presenter too early. Thanks very much!
