### ISSUE TITLE
NullPointerException on Presenter#onViewAttached while using android.app.Activity

### ISSUE THREAD

**Issue by RiccardoM** [6thsolution/EasyMVP#34]
**Bug**
Today I found out that the following code produces a `NullPointerException`:
```java
public class WebViewActivity extends android.app.Activity implements WebViewActivityView {
    @Presenter WebViewActivityPresenter presenter;
}
```

**How to replicate**
The exception can be replacated as follows:
1. Start the activity.
2. Rotate the screen.

At this point, the following exception is thrown:
`ComponentInfo: java.lang.NullPointerException: Attempt to invoke virtual method 'void WebViewActivityPresenter.onViewAttached(WebViewActivityView)' on a null object reference`

**How to avoid**
I've found out that if `android.support.v7.app.AppCompatActivity` is used instead of `android.app.Activity`, then the exception won't be thrown, and everything executes smoothly.
  
I think that this is a pretty big bug, which may cause a lot of problems, and should be solved as soon as possibile. @SaeedMasoumi

**Comment by SaeedMasoumi** [comment]
@RiccardoM Yeah there is an issue while using `Loader` inside `android.app.Activity`. I didn't found any solution on the web and people suggested to use `AppCompatActivity` instead.

Also see these two tests, [SimpleActivity](https://github.com/6thsolution/EasyMVP/blob/master/easymvp-test/src/main/java/com/sixthsolution/easymvp/test/SimpleActivity.java#L53) and [SimpleAppCompatTest](https://github.com/6thsolution/EasyMVP/blob/master/easymvp-test/src/main/java/com/sixthsolution/easymvp/test/SimpleAppCompatActivity.java)
EasyMVP generates same codes for these two classes but the problems is the Loader manager in `android.app.Activity`,  the `AppCompatActivity` replaced  his own manager. I don't know it's fixed in new android releases or not.
